/* Generated by cbindgen from blockwork-ffi/src/lib.rs. Do not edit by hand. */

#ifndef BLOCKWORK_FFI_H
#define BLOCKWORK_FFI_H

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

#ifdef __cplusplus
extern "C" {
#endif // __cplusplus

/**
 * Registers the callback that formatted `tracing` events are routed
 * through. Call once, before `blockwork_init`, from the host's main thread.
 * `callback` receives one NUL-terminated line per event; null disables
 * logging.
 */
void blockwork_set_log_callback(void (*callback)(const char*));

/**
 * Must be called once, from the host's main thread, before any other
 * `blockwork_*` function (macOS's Accessibility prompt requires the main
 * thread). `config_dir_override_utf8` may be null/empty to use the OS
 * config directory; pass a path to redirect macro/settings storage
 * elsewhere (e.g. a Wine `Z:`-mapped path under Proton).
 * `linux_bridge_resource_path_utf8` is the Windows-side path to the
 * bundled `linux-input.so`, used only when running under Wine on a Linux
 * host; ignored (may be null) otherwise.
 *
 * Returns 0 on success, -1 if no input backend could be created for this
 * platform.
 */
int32_t blockwork_init(const char *config_dir_override_utf8,
                       const char *linux_bridge_resource_path_utf8);

/**
 * Starts recording into the currently-selected macro's timing baseline.
 * Mirrors the desktop app's `StartRecordingImmediate` hotkey handler.
 */
int32_t blockwork_start_recording(void);

/**
 * Stops recording and, if anything was captured, appends it to the
 * currently-selected macro's recording target and saves it to disk.
 * Returns the number of instructions saved (0 if nothing was captured),
 * or a negative error code if recording state couldn't be resolved/saved.
 */
int32_t blockwork_stop_recording(void);

/**
 * Runs a macro on a background thread — the explicit `id_utf8` if given
 * (nullable), otherwise the currently-selected macro. Loop mode is read
 * live from the shared settings file on every call. Returns immediately;
 * interrupt with `blockwork_stop_loop`.
 *
 * `elapsed_overshoot_ms` (>= 0, milliseconds): how much real time had
 * already passed, before this call, since playback was supposed to
 * start — pass 0 if not applicable. Backdates the run's first `Wait`
 * deadline to the intended start instant via `Macro::run_with_offset`.
 */
int32_t blockwork_run_macro(const char *id_utf8, double elapsed_overshoot_ms);

/**
 * Stops every in-flight run (single or looping) started via
 * `blockwork_run_macro`.
 */
int32_t blockwork_stop_loop(void);

/**
 * Sets the global playback speed multiplier, applied on top of each
 * macro's own `speed_multiplier`. Clamped to `SPEED_MULTIPLIER_RANGE`
 * (0.1x-10x). Takes effect on the next `blockwork_run_macro` call; does not
 * affect a run already in flight. Always returns 0.
 */
int32_t blockwork_set_speed_multiplier(double multiplier);

/**
 * Creates a new macro (name defaults to `"New Macro"` if `name_utf8` is
 * null/empty), saves it, and marks it the currently-selected macro.
 * Returns 0 on success, -1 if the new macro couldn't be saved.
 */
int32_t blockwork_create_macro(const char *name_utf8);

/**
 * Returns a heap-allocated, NUL-terminated UTF-8 JSON array of every saved
 * macro, as `[{"id": "...", "name": "..."}, ...]`, ordered by
 * case-insensitive name then id. Never null (an empty library serializes
 * to `"[]"`); caller must free the result with `blockwork_free_string`.
 */
char *blockwork_list_macros(void);

/**
 * Returns a heap-allocated, NUL-terminated UTF-8 string with the id of the
 * currently-selected macro, or null if none is selected. Caller must free a
 * non-null result with `blockwork_free_string`.
 */
char *blockwork_get_selected_macro_id(void);

/**
 * Marks the macro with the given id as the currently-selected one — the
 * target `blockwork_run_macro(NULL)`, `blockwork_stop_recording`, and
 * `blockwork_clear_recording_target_instructions` resolve against. Returns 0
 * on success, -1 if no macro with that id exists.
 */
int32_t blockwork_select_macro(const char *id_utf8);

/**
 * Renames the currently-selected macro and saves it. `name_utf8`'s
 * surrounding whitespace is trimmed; a null/empty/whitespace-only name is
 * rejected. Returns 0 on success, or a negative error code: -1 no macro
 * currently selected, -2 selected macro couldn't be loaded, -3 the
 * trimmed name was empty, -4 couldn't be saved back to disk.
 */
int32_t blockwork_rename_macro(const char *name_utf8);

/**
 * Permanently deletes the currently-selected macro's file from disk and
 * clears the selection. The host is expected to confirm with the user
 * before calling this. Returns 0 on success, or a negative error code: -1
 * no macro currently selected, -2 selected macro couldn't be loaded, -3
 * couldn't be removed from disk.
 */
int32_t blockwork_delete_macro(void);

/**
 * Clears every recorded instruction from the currently-selected macro's
 * recording-target strand only (see `Macro::recording_target_mut`), other
 * strands untouched. Keeps the target strand's own `WhenRan`/`BlockHeader`
 * if it has one. Returns the number of instructions removed (0 if the
 * strand had none beyond its header), or a negative error code: -1 no
 * macro currently selected, -2 selected macro couldn't be loaded, -3
 * couldn't be saved back to disk.
 */
int32_t blockwork_clear_recording_target_instructions(void);

/**
 * Frees a string previously returned by `blockwork_list_macros` or
 * `blockwork_get_selected_macro_id`. Safe to call with null (no-op).
 */
void blockwork_free_string(char *ptr);

/**
 * True if input capture/emission couldn't be set up — on macOS this means
 * Accessibility access hasn't been granted (to the host process); the
 * caller should surface a UI prompt to check System Settings.
 */
bool blockwork_grab_failed(void);

/**
 * Trivial ABI/link smoke-test symbol.
 */
int32_t blockwork_ping(void);

#ifdef __cplusplus
}  // extern "C"
#endif  // __cplusplus

#endif  /* BLOCKWORK_FFI_H */
